import turtle as trtl

painter = trtl.Turtle()
painter.pensize(13)
painter.turtlesize(1)
#i want to draw the stick figure not centered so i have room for the tower
painter.penup()
painter.backward(100)
painter.pendown()
#start by making the stick figure and drawing the torso
painter.pencolor("red")
painter.right(90)
painter.backward(100)
painter.left(90)
#now the head
painter.pensize(6)
painter.pencolor("black")
painter.circle(80)
#and face
painter.penup()
painter.left(90)
painter.forward(40)
painter.left(90)
painter.forward(20)
painter.pencolor("pink")
painter.right(270)
#mouth
painter.pendown()
painter.circle(20,180)
painter.penup()
painter.forward(40)
painter.right(90)
painter.forward(15)
painter.pencolor("brown")
#eyes
painter.pendown()
painter.fillcolor("maroon")
painter.begin_fill()
painter.circle(10)
painter.end_fill()
painter.penup()
painter.right(180)
painter.forward(70)
painter.right(180)
painter.pendown()
painter.begin_fill()
painter.circle(10)
painter.end_fill()
painter.penup()
painter.forward(35)
painter.right(90)
painter.forward(90)
painter.pendown()
painter.pencolor("red")
painter.pensize(13)
painter.forward(200)
#with the torso done I move onto the legs
painter.color("blue")
painter.right(25)
painter.forward(150)
painter.right(180)
painter.forward(150)
painter.right(130)
painter.forward(150)
painter.right(180)
painter.forward(150)
painter.right(25)
painter.penup()
painter.forward(130)
#onto the arms
painter.pendown()
painter.color("black")
painter.right(55)
painter.forward(150)
painter.backward(150)
painter.left(205)
painter.forward(150)
#flying W
painter.pensize(10)
painter.penup()
painter.left(120)
painter.forward(200)
painter.left(90)
painter.forward(100)
painter.right(90)
painter.pendown()
painter.forward(50)
painter.right(65)
painter.forward(50)
painter.left(130)
painter.forward(50)
painter.right(130)
painter.forward(50)
painter.left(130)
painter.forward(50)
painter.right(65)
painter.forward(50)
#second lines
painter.penup()
painter.right(90)
painter.forward(13)
painter.right(90)
painter.pendown()
painter.forward(50)
painter.penup()
painter.forward(85)
painter.pendown()
painter.forward(50)


wn = trtl.Screen()
wn.mainloop()
